# ============================================================================================
# Script:  DRIMSeq_stageR_analysis.R
# Purpose: using input files generated by DRIMSeq_input_generation.R, Differential Isofrom Usage
# analysis is performed, followed by futher exploration with stageR
# help from: https://www.bioconductor.org/packages/release/bioc/vignettes/DRIMSeq/inst/doc/DRIMSeq.pdf
# Author:  Valeria Famà
# ============================================================================================

##################################################
########## IMPORT and READ FILES #################
##################################################
library(ggplot2)
library(stageR)
library(clusterProfiler)
library(org.Hs.eg.db)
library(DRIMSeq)

BASEDIR <- "/projects/CGS_shared/vfama/BRIGHT_PROJECT/"

esegui_DIU_cline <- function(cline, BASEDIR, alpha = 0.05, delta_thresh = 0.10) {

  outdir <- file.path(BASEDIR, "DIU", cline)
  counts_input <- read.table(file.path(outdir, paste0(cline, "_DMSO_STM_Tx_counts.tsv")), header = TRUE)
  metadata     <- read.table(file.path(outdir, paste0(cline, "_DRIMSEQ_metadata.tsv")), header = TRUE)

  d <- dmDSdata(counts = counts_input, samples = metadata)

  # filtering: min campioni per gruppo (qui: n. repliche del gruppo più piccolo)
  min_sample_gene <- sum(table(DRIMSeq::samples(d)$group))
  min_sample_tx   <- min(table(DRIMSeq::samples(d)$group))

  d <- dmFilter(d, min_samps_gene_expr = min_sample_gene, min_samps_feature_expr = min_sample_tx,
                min_gene_expr = 10, min_feature_expr = 10)

  design_full <- model.matrix(~ group, data = DRIMSeq::samples(d))
  set.seed(123)
  d <- dmPrecision(d, design = design_full, BPPARAM = BiocParallel::MulticoreParam(workers = 8))
  d <- dmFit(d, design = design_full, verbose = 1)

  design_null <- model.matrix(~ 1, data = DRIMSeq::samples(d))
  d <- dmTest(d, design = design_null)

  ## stageR (identico allo script precedente) ##
  pScreen <- results(d)$pvalue
  names(pScreen) <- results(d)$gene_id
  pConfirmation <- matrix(results(d, level = "feature")$pvalue, ncol = 1)
  rownames(pConfirmation) <- results(d, level = "feature")$feature_id
  tx2gene <- results(d, level = "feature")[, c("feature_id", "gene_id")]

  tx_gene <- tx2gene[[2]][match(rownames(pConfirmation), tx2gene[[1]])]
  valid_screen_genes <- names(pScreen)[!is.na(pScreen)]
  keep_tx <- (tx_gene %in% valid_screen_genes & !is.na(tx_gene) & complete.cases(pConfirmation))
  pConfirmation2 <- pConfirmation[keep_tx, , drop = FALSE]
  tx2gene2 <- data.frame(feature_id = rownames(pConfirmation)[keep_tx], gene_id = tx_gene[keep_tx],
                        stringsAsFactors = FALSE)
  pScreen2 <- pScreen[valid_screen_genes]

  n_tx <- table(tx2gene2$gene_id)
  valid_genes <- names(n_tx[n_tx >= 2])
  pScreen2 <- pScreen2[names(pScreen2) %in% valid_genes]
  keep_tx2 <- tx2gene2$gene_id %in% valid_genes
  tx2gene2 <- tx2gene2[keep_tx2, , drop = FALSE]
  pConfirmation2 <- pConfirmation2[keep_tx2, , drop = FALSE]

  stopifnot(
    !anyNA(pScreen2), !anyNA(pConfirmation2), !anyNA(tx2gene2),
    identical(rownames(pConfirmation2), as.character(tx2gene2$feature_id)),
    all(tx2gene2$gene_id %in% names(pScreen2)),
    all(table(tx2gene2$gene_id) >= 2)
  )

  stageRObj <- stageRTx(pScreen = pScreen2, pConfirmation = pConfirmation2,
                        pScreenAdjusted = FALSE, tx2gene = tx2gene2)
  stageRObj <- stageWiseAdjustment(stageRObj, method = "dtu", alpha = alpha, allowNA = FALSE)
  padj <- getAdjustedPValues(stageRObj, order = TRUE, onlySignificantGenes = FALSE)

  ## effect size: delta usage STORM - DMSO ##
  prop <- DRIMSeq::proportions(d)
  sample_info <- DRIMSeq::samples(d)
  sample_info$sample_id <- as.character(sample_info$sample_id)

  ids_dmso  <- sample_info$sample_id[sample_info$group == "DMSO"]
  ids_storm <- sample_info$sample_id[sample_info$group == "STM"]
  stopifnot(all(c(ids_dmso, ids_storm) %in% colnames(prop)))

  prop_dmso  <- rowMeans(prop[, ids_dmso,  drop = FALSE])
  prop_storm <- rowMeans(prop[, ids_storm, drop = FALSE])

  effect_table <- data.frame(
    geneID = as.character(prop$gene_id),
    txID   = as.character(prop$feature_id),
    proportion_DMSO  = prop_dmso,
    proportion_STORM = prop_storm,
    delta_usage     = prop_storm - prop_dmso,      # STORM - DMSO
    abs_delta_usage = abs(prop_storm - prop_dmso)
  )

  ## combina con statistiche DRIMSeq ##
  padj_df <- as.data.frame(padj)
  padj_df$geneID <- as.character(padj_df$geneID)
  padj_df$txID   <- as.character(padj_df$txID)

  tx_res <- results(d, level = "feature")
  tx_stats <- data.frame(geneID = as.character(tx_res$gene_id), txID = as.character(tx_res$feature_id),
                         tx_lr = tx_res$lr, tx_pvalue_raw = tx_res$pvalue)

  gene_res <- results(d)
  gene_stats <- data.frame(geneID = as.character(gene_res$gene_id),
                           gene_lr = gene_res$lr, gene_pvalue_raw = gene_res$pvalue)

  final_table <- merge(padj_df, effect_table, by = c("geneID","txID"), all.x = TRUE, sort = FALSE)
  final_table <- merge(final_table, tx_stats,  by = c("geneID","txID"), all.x = TRUE, sort = FALSE)
  final_table <- merge(final_table, gene_stats, by = "geneID", all.x = TRUE, sort = FALSE)

  a <- getAlpha(stageRObj)
  final_table$gene_significant <- !is.na(final_table$gene) & final_table$gene <= a
  final_table$tx_significant   <- !is.na(final_table$transcript) & final_table$transcript <= a
  final_table$cell_line <- cline

  priority_table <- subset(final_table, tx_significant & abs(delta_usage) >= delta_thresh)
  priority_table <- priority_table[order(-abs(priority_table$delta_usage), priority_table$txID), ]

  write.table(final_table, file.path(outdir, paste0(cline, "_DIU_DRIMSeq_stageR_full.tsv")),
              sep = "\t", row.names = FALSE, quote = FALSE)
  write.table(priority_table, file.path(outdir, paste0(cline, "_prioritized_DIUs_DMSO_vs_STM.tsv")),
              sep = "\t", row.names = FALSE, quote = FALSE)

  invisible(list(d = d, final_table = final_table, priority_table = priority_table))
}

# esegui per tutte le 6 linee e tieni i risultati in una lista
cell_lines <- c("BT483", "MCF7", "T47D", "MDAMB231", "SUM159", "BT549")
risultati_DIU <- setNames(lapply(cell_lines, esegui_DIU_cline, BASEDIR = BASEDIR), cell_lines)

# tabella combinata di tutte le priority table, con colonna cell_line già presente
priority_all <- do.call(rbind, lapply(risultati_DIU, `[[`, "priority_table"))
write.table(priority_all, file.path(BASEDIR, "DIU", "all_cell_lines_prioritized_DIUs_DMSO_vs_STM.tsv"),
            sep = "\t", row.names = FALSE, quote = FALSE)

